version: "2"
services:
  adminer:
    image: "adminer"
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      POSTGRES_PASSWORD: password
    links:
      - db:db

  db:
    image: "postgres:17"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ../data/dev/db:/var/lib/postgresql
      - ./dev/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432
