version: '2'
services:
  adminer:
    image: 'adminer'
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      POSTGRES_PASSWORD: password
    links:
      - db:db

  db:
    image: 'postgres:11'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ../data/prod/db:/var/lib/postgresql
      - ./prod/initdb:/docker-entrypoint-initdb.d:ro

  migrator:
    build:
      context: ../bot
      dockerfile: prod.dockerfile
    command: bun run migrate
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/bot
      MIGRATE_DATABASE_URL: postgres://postgres:password@db:5432/bot

  bot:
    build:
      context: ../bot
      dockerfile: prod.dockerfile
    depends_on:
      - db
      - migrator
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/bot
      MIGRATE_DATABASE_URL: postgres://postgres:password@db:3307/bot
